package:
  name: rna-hipp-explorer
  version: 0.0.2

source:
  git_url: git@github.com:stephaaaaan/RNAHippExplorer.git

requirements:
  host:
    - python
    - setuptools
  build:
    - python
  run:
    - python
    - pandas
    - pyqt
    - PyQtWebEngine
about:
  home: https://github.com/stephaaaaan/RNAHippExplorer
  license: MIT
  summary: 'Browse RNA expression and alternative splicing for Hippocampus & Cortex'