package:
  name: rna-expression-splicing-explorer
  version: 0.0.2

source:
  git_url: https://github.com/stephaaaaan/rna-expression-splicing-explorer.git
  git_rev: main

requirements:
  host:
    - python
    - setuptools
  build:
    - python
  run:
    - python
    - pandas
    - pyqt
    - PyQtWebEngine
about:
  home: https://github.com/stephaaaaan/RNAHippExplorer
  license: MIT
  summary: 'Browse RNA expression and alternative splicing for Hippocampus & Cortex'